import json

additional_companies = [
    # Global Tech
    {"name": "Google", "url": "https://careers.google.com"},
    {"name": "Microsoft", "url": "https://careers.microsoft.com"},
    {"name": "Apple", "url": "https://www.apple.com/careers"},
    {"name": "Meta", "url": "https://www.metacareers.com"},
    {"name": "Amazon", "url": "https://amazon.jobs"},
    {"name": "Netflix", "url": "https://jobs.netflix.com"},
    {"name": "Spotify", "url": "https://lifeatspotify.com"},
    {"name": "Airbnb", "url": "https://careers.airbnb.com"},
    {"name": "Uber", "url": "https://www.uber.com/careers"},
    {"name": "Stripe", "url": "https://stripe.com/jobs"},
    {"name": "Twitter", "url": "https://careers.twitter.com"},
    {"name": "Snap", "url": "https://careers.snap.com"},
    {"name": "TikTok", "url": "https://careers.tiktok.com"},
    {"name": "LinkedIn", "url": "https://careers.linkedin.com"},
    {"name": "Dropbox", "url": "https://jobs.dropbox.com"},
    {"name": "Slack", "url": "https://slack.com/careers"},
    {"name": "Atlassian", "url": "https://www.atlassian.com/company/careers"},
    {"name": "Twilio", "url": "https://www.twilio.com/company/jobs"},
    {"name": "Zoom", "url": "https://careers.zoom.us"},
    {"name": "Shopify", "url": "https://www.shopify.com/careers"},
    {"name": "Square", "url": "https://careers.squareup.com"},
    {"name": "Pinterest", "url": "https://careers.pinterest.com"},
    {"name": "Reddit", "url": "https://www.redditinc.com/careers"},
    {"name": "Discord", "url": "https://discord.com/careers"},
    {"name": "GitHub", "url": "https://github.com/about/careers"},
    {"name": "GitLab", "url": "https://about.gitlab.com/jobs/"},
    {"name": "Figma", "url": "https://www.figma.com/careers/"},
    {"name": "Canva", "url": "https://www.canva.com/careers/"},
    {"name": "Notion", "url": "https://www.notion.so/careers"},
    {"name": "Miro", "url": "https://miro.com/careers/"},
    {"name": "Vercel", "url": "https://vercel.com/careers"},
    {"name": "Supabase", "url": "https://supabase.com/careers"},
    {"name": "Netlify", "url": "https://www.netlify.com/careers/"},
    {"name": "Cloudflare", "url": "https://www.cloudflare.com/careers/"},
    {"name": "Fastly", "url": "https://www.fastly.com/about/careers"},
    {"name": "Datadog", "url": "https://careers.datadoghq.com/"},
    {"name": "Snowflake", "url": "https://careers.snowflake.com/"},
    {"name": "MongoDB", "url": "https://www.mongodb.com/careers"},
    {"name": "Elastic", "url": "https://www.elastic.co/about/careers"},
    {"name": "Splunk", "url": "https://www.splunk.com/en_us/careers.html"},
    {"name": "Palantir", "url": "https://www.palantir.com/careers/"},
    {"name": "Coinbase", "url": "https://www.coinbase.com/careers"},
    {"name": "Kraken", "url": "https://www.kraken.com/careers"},
    {"name": "Binance", "url": "https://www.binance.com/en/careers"},
    {"name": "OpenAI", "url": "https://openai.com/careers"},
    {"name": "Anthropic", "url": "https://www.anthropic.com/careers"},
    {"name": "Hugging Face", "url": "https://huggingface.co/careers"},
    {"name": "Midjourney", "url": "https://www.midjourney.com/"},
    {"name": "Stability AI", "url": "https://stability.ai/careers"},
    {"name": "Scale AI", "url": "https://scale.com/careers"},
    
    # European Tech
    {"name": "Klarna", "url": "https://www.klarna.com/careers/"},
    {"name": "Revolut", "url": "https://www.revolut.com/careers/"},
    {"name": "N26", "url": "https://n26.com/en-eu/careers"},
    {"name": "Monzo", "url": "https://monzo.com/careers/"},
    {"name": "Deliveroo", "url": "https://careers.deliveroo.co.uk/"},
    {"name": "Delivery Hero", "url": "https://careers.deliveryhero.com/"},
    {"name": "Just Eat Takeaway", "url": "https://careers.justeattakeaway.com/"},
    {"name": "Zalando", "url": "https://jobs.zalando.com/"},
    {"name": "HelloFresh", "url": "https://careers.hellofresh.com/"},
    {"name": "Adyen", "url": "https://careers.adyen.com/"},
    {"name": "Criteo", "url": "https://careers.criteo.com/"},
    {"name": "Booking.com", "url": "https://careers.booking.com/"},
    {"name": "Skyscanner", "url": "https://www.skyscanner.net/jobs/"},
    {"name": "Trivago", "url": "https://company.trivago.com/careers/"},
    {"name": "Babbel", "url": "https://jobs.babbel.com/"},
    {"name": "Duolingo", "url": "https://careers.duolingo.com/"},
    {"name": "Vinted", "url": "https://www.vinted.com/jobs"},
    {"name": "Trade Republic", "url": "https://careers.traderepublic.com/"},
    {"name": "Bitpanda", "url": "https://www.bitpanda.com/en/careers"},
    {"name": "Mollie", "url": "https://jobs.mollie.com/"},
    {"name": "Checkout.com", "url": "https://www.checkout.com/careers"},
    {"name": "Wise", "url": "https://wise.jobs/"},
    {"name": "Plaid", "url": "https://plaid.com/careers/"},
    {"name": "Affirm", "url": "https://www.affirm.com/careers"},
    {"name": "Robinhood", "url": "https://careers.robinhood.com/"},
    
    # Turkish Tech / Startups
    {"name": "Martı", "url": "https://www.marti.tech/kariyer"},
    {"name": "Papel", "url": "https://papel.com.tr"},
    {"name": "Ozan SuperApp", "url": "https://www.ozan.com/tr/kariyer"},
    {"name": "Midas", "url": "https://www.getmidas.com/kariyer"},
    {"name": "Apsiyon", "url": "https://www.apsiyon.com/kariyer"},
    {"name": "Kolay İK", "url": "https://kolayik.com/kariyer"},
    {"name": "Evreka", "url": "https://evreka.co/careers/"},
    {"name": "Vispera", "url": "https://vispera.co/careers"},
    {"name": "Thread In Motion", "url": "https://www.threadinmotion.com"},
    {"name": "V-Count", "url": "https://v-count.com/careers/"},
    {"name": "Tarfin", "url": "https://tarfin.com/kariyer"},
    {"name": "Figopara", "url": "https://figopara.com/kariyer"},
    {"name": "Norma", "url": "https://www.norma.co/tr/kariyer"},
    {"name": "Lidio", "url": "https://lidio.com"},
    {"name": "Paycore", "url": "https://www.paycore.com/kariyer/"},
    {"name": "Uyumsoft", "url": "https://www.uyumsoft.com/kariyer"},
    {"name": "Logo Yazılım", "url": "https://www.logo.com.tr/kariyer"},
    {"name": "Etiya", "url": "https://www.etiya.com/careers"},
    {"name": "Netaş", "url": "https://netas.com.tr/kariyer/"},
    {"name": "Karel", "url": "https://www.karel.com.tr/kariyer"},
    {"name": "OBSS", "url": "https://obss.tech/careers/"},
    {"name": "Definex", "url": "https://teamdefinex.com/careers"},
    {"name": "Commencis", "url": "https://www.commencis.com/careers/"},
    {"name": "KoçDigital", "url": "https://kocdigital.com.tr/kariyer"},
    {"name": "KoçSistem", "url": "https://www.kocsistem.com.tr/kariyer"},
    {"name": "SabancıDx", "url": "https://www.sabancidx.com/kariyer"},
    {"name": "Innova", "url": "https://www.innova.com.tr/tr/kariyer"},
    {"name": "Turkcell Teknoloji", "url": "https://kariyer.turkcell.com.tr/"},
    {"name": "Vodafone Teknoloji", "url": "https://careers.vodafone.com/"},
    {"name": "Türk Telekom", "url": "https://kariyer.turktelekom.com.tr/"},
    {"name": "Enoca", "url": "https://enoca.com/kariyer/"},
    {"name": "Armut", "url": "https://armut.com/kariyer"},
    {"name": "Tapu.com", "url": "https://www.tapu.com/"},
    {"name": "Zingat", "url": "https://www.zingat.com/"},
    {"name": "Arabam.com", "url": "https://www.arabam.com/"},
    {"name": "Kariyer.net", "url": "https://www.kariyer.net/"},
    {"name": "Yenibiris", "url": "https://www.yenibiris.com/"},
    {"name": "Secretcv", "url": "https://www.secretcv.com/"},
    {"name": "Eleman.net", "url": "https://www.eleman.net/"},
    {"name": "Cimri", "url": "https://www.cimri.com/"},
    {"name": "Akakce", "url": "https://www.akakce.com/"},
    {"name": "PttAVM", "url": "https://www.pttavm.com/"},
    {"name": "Biletix", "url": "https://www.biletix.com/"},
    {"name": "Biletall", "url": "https://www.biletall.com/"},
    {"name": "Obilet", "url": "https://www.obilet.com/"},
    {"name": "Turna", "url": "https://www.turna.com/"},
    {"name": "Enuygun", "url": "https://www.enuygun.com/"},
    {"name": "Tatilsepeti", "url": "https://www.tatilsepeti.com/"},
    {"name": "Etstur", "url": "https://www.etstur.com/"},
    {"name": "Setur", "url": "https://www.setur.com.tr/"},
    {"name": "Pegasus", "url": "https://www.flypgs.com/kariyer"},
    {"name": "Turkish Airlines Technology", "url": "https://careers.turkishairlines.com/"},
    {"name": "SunExpress", "url": "https://www.sunexpress.com/tr/kariyer/"},
    {"name": "Corendon", "url": "https://www.corendonairlines.com/tr/kariyer"},
    {"name": "Ford Otosan", "url": "https://www.fordotosan.com.tr/tr/kariyer"},
    {"name": "Tofaş", "url": "https://www.tofas.com.tr/Kariyer"},
    {"name": "Otokar", "url": "https://www.otokar.com.tr/kariyer"},
    {"name": "Karsan", "url": "https://www.karsan.com/tr/kariyer"},
    {"name": "Togg", "url": "https://togg.com.tr/kariyer"},
    {"name": "Vestel", "url": "https://kariyer.vestel.com.tr/"},
    {"name": "Arçelik", "url": "https://www.arcelikglobal.com/tr/kariyer/"},
    {"name": "Beko", "url": "https://www.bekocareers.com/"},
    {"name": "Aselsan", "url": "https://www.aselsan.com/tr/kariyer"},
    {"name": "Havelsan", "url": "https://www.havelsan.com.tr/kariyer"},
    {"name": "Roketsan", "url": "https://www.roketsan.com.tr/tr/kariyer"},
    {"name": "Tusas", "url": "https://www.tusas.com/kariyer"},
    {"name": "Baykar", "url": "https://kariyer.baykartech.com/"},
    {"name": "STM", "url": "https://www.stm.com.tr/tr/kariyer"},
    {"name": "Meteksan", "url": "https://www.meteksan.com/tr/kariyer"},
    {"name": "Ctech", "url": "https://ctech.com.tr/tr/kariyer"},
    {"name": "Pavo Tasarım", "url": "https://www.pavotek.com.tr/kariyer/"},
    {"name": "Tarentum", "url": "https://www.tarentum.io/careers"},
    {"name": "Akinon", "url": "https://akinon.com/careers/"},
    {"name": "Inveon", "url": "https://www.inveon.com/careers/"},
    {"name": "IdeaSoft", "url": "https://www.ideasoft.com.tr/kariyer/"},
    {"name": "Ticimax", "url": "https://www.ticimax.com/kariyer/"},
    {"name": "T-Soft", "url": "https://www.tsoft.com.tr/kariyer.php"},
    {"name": "Proje Yönetim", "url": "https://www.projeyonetim.com/"},
    {"name": "Pisano", "url": "https://www.pisano.co/careers"},
    {"name": "Evam", "url": "https://evam.com/careers/"},
    {"name": "Datarobot", "url": "https://www.datarobot.com/careers/"},
    {"name": "Zeplin", "url": "https://zeplin.io/careers/"},
    {"name": "Picnic", "url": "https://picnic.app/careers/"},
    {"name": "Delivery Hero", "url": "https://careers.deliveryhero.com/"},
    {"name": "Just Eat", "url": "https://careers.justeattakeaway.com/"},
    {"name": "MUBI", "url": "https://mubi.com/jobs"},
    {"name": "BluTV", "url": "https://www.blutv.com/"},
    {"name": "Exxen", "url": "https://www.exxen.com/"},
    {"name": "Gain", "url": "https://www.gain.tv/"},
    {"name": "Digiturk", "url": "https://www.digiturk.com.tr/"},
    {"name": "D-Smart", "url": "https://www.dsmart.com.tr/"},
    {"name": "Turkcell TV+", "url": "https://tvplus.com.tr/"},
    {"name": "Kafa Topu", "url": "https://masomo.com/"},
    {"name": "TaleWorlds", "url": "https://www.taleworlds.com/en/Careers"},
    {"name": "Crytek", "url": "https://www.crytek.com/career"},
    {"name": "Peak", "url": "https://peak.com/"},
    {"name": "Dream Games", "url": "https://dreamgames.com/careers/"},
    {"name": "Spyke Games", "url": "https://spykegames.com/"},
    {"name": "Bigger Games", "url": "https://biggergames.com/careers"},
    {"name": "Rollic", "url": "https://rollicgames.com/"},
    {"name": "Gram Games", "url": "https://gram.gs/careers/"},
    {"name": "Ruby Games", "url": "https://rubygames.com/"},
    {"name": "Fugo Games", "url": "https://fugogames.com/"},
    {"name": "Ace Games", "url": "https://ace.games/"},
    {"name": "Zuuks Games", "url": "https://www.zuuks.com/"},
    {"name": "Gripati", "url": "https://gripati.com/"},
    {"name": "Tiramisu", "url": "https://tiramisu.game/"},
    {"name": "Alictus", "url": "https://alictus.com/"},
    {"name": "Garanti BBVA", "url": "https://kariyer.garantibbva.com.tr/"},
    {"name": "İş Bankası", "url": "https://kariyer.isbank.com.tr/"},
    {"name": "Yapı Kredi", "url": "https://www.yapikredikariyer.com.tr/"},
    {"name": "Akbank", "url": "https://kariyer.akbank.com/"},
    {"name": "QNB Finansbank", "url": "https://www.qnbfinansbank.com/kariyer"},
    {"name": "DenizBank", "url": "https://www.denizbank.com/hakkimizda/kariyer"},
    {"name": "VakıfBank", "url": "https://www.vakifbank.com.tr/kariyer.aspx"},
    {"name": "Halkbank", "url": "https://www.halkbank.com.tr/tr/hakkimizda/insan-kaynaklari/kariyer.html"},
    {"name": "Ziraat Bankası", "url": "https://www.ziraatbank.com.tr/tr/bankamiz/insan-kaynaklari"},
    {"name": "TEB", "url": "https://www.teb.com.tr/kariyer/"},
    {"name": "Kuveyt Türk", "url": "https://www.kuveytturk.com.tr/hakkimizda/insan-kaynaklari"},
    {"name": "Albaraka Türk", "url": "https://www.albarakaturk.com.tr/insan-kaynaklari"},
    {"name": "Türkiye Finans", "url": "https://www.turkiyefinans.com.tr/tr-tr/hakkimizda/insan-kaynaklari/Sayfalar/kariyer.aspx"},
    {"name": "FibaBanka", "url": "https://www.fibabanka.com.tr/hakkimizda/insan-kaynaklari/fibabankada-kariyer"},
    {"name": "OdeaBank", "url": "https://www.odeabank.com.tr/hakkimizda/insan-kaynaklari"},
    {"name": "Burgan Bank", "url": "https://www.burgan.com.tr/insan-kaynaklari/kariyer"},
    {"name": "Alternatif Bank", "url": "https://www.alternatifbank.com.tr/hakkimizda/insan-kaynaklari"},
    {"name": "Aktif Bank", "url": "https://www.aktifbank.com.tr/tr/hakkimizda/insan-kaynaklari"},
    {"name": "Papara", "url": "https://www.papara.com/kariyer"},
    {"name": "Ininal", "url": "https://www.ininal.com/kariyer"},
    {"name": "Param", "url": "https://param.com.tr/kariyer"},
    {"name": "PayTR", "url": "https://www.paytr.com/kariyer"},
    {"name": "Iyzico", "url": "https://www.iyzico.com/kariyer"},
    {"name": "Ozan", "url": "https://www.ozan.com/tr/kariyer"},
    {"name": "Tosla", "url": "https://tosla.com/"},
    {"name": "Sipay", "url": "https://www.sipay.com.tr/kariyer"},
    {"name": "Moka", "url": "https://moka.com/"},
    {"name": "Birleşik Ödeme", "url": "https://www.unitedpayment.com/"},
    {"name": "Elekse", "url": "https://elekse.com/"},
    {"name": "Turkcell Paycell", "url": "https://paycell.com.tr/"},
    {"name": "Vodafone Pay", "url": "https://www.vodafonepay.com.tr/"},
    {"name": "BtcTurk", "url": "https://www.btcturk.com/kariyer"},
    {"name": "Paribu", "url": "https://www.paribu.com/kariyer"},
    {"name": "Bitexen", "url": "https://www.bitexen.com/kariyer"},
    {"name": "Icrypex", "url": "https://www.icrypex.com/"},
    {"name": "Tomya", "url": "https://www.tomya.com/"},
    {"name": "BtcTurk PRO", "url": "https://pro.btcturk.com/"},
    {"name": "Binance TR", "url": "https://www.trbinance.com/"},
    {"name": "Hepsiburada", "url": "https://www.hepsiburada.com/kariyer"},
    {"name": "Trendyol", "url": "https://careers.trendyol.com/"},
    {"name": "Getir", "url": "https://careers.getir.com/"},
    {"name": "Yemeksepeti", "url": "https://careers.deliveryhero.com/yemeksepeti/"},
    {"name": "Sahibinden", "url": "https://kariyer.sahibinden.com/"},
    {"name": "N11", "url": "https://kariyer.n11.com/"},
    {"name": "Çiçeksepeti", "url": "https://kariyer.ciceksepeti.com/"},
    {"name": "Boyner", "url": "https://kariyer.boyner.com.tr/"},
    {"name": "Beymen", "url": "https://www.beymen.com/"},
    {"name": "Vakko", "url": "https://www.vakko.com/"},
    {"name": "LC Waikiki", "url": "https://corporate.lcwaikiki.com/Kariyer"},
    {"name": "DeFacto", "url": "https://kariyer.defacto.com.tr/"},
    {"name": "Koton", "url": "https://kariyer.koton.com/"},
    {"name": "Mavi", "url": "https://www.mavi.com/"}
]

# Ensure uniqueness and append
try:
    with open('companies.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
except Exception:
    data = []

existing_names = set(c['name'].lower() for c in data)

count = 0
for comp in additional_companies:
    if comp['name'].lower() not in existing_names:
        comp['logo'] = comp.get('logo', '🏢')
        data.append(comp)
        existing_names.add(comp['name'].lower())
        count += 1

with open('companies.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {count} new companies successfully. Total companies now: {len(data)}")
